name: silver_genie
description: SilverGenie
version: 1.0.0+17
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  connectivity_plus: ^6.0.3
  country_code_picker: ^3.0.0
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.2.2
  dio_http2_adapter: ^2.3.1+1
  easy_localization: ^3.0.5
  envied: ^0.5.3
  firebase_analytics: ^10.6.3
  firebase_core: ^2.32.0
  firebase_crashlytics: ^3.4.3
  firebase_in_app_messaging: ^0.7.4+17
  firebase_messaging: ^14.7.19
  firebase_performance: ^0.9.3+3
  firebase_performance_dio: ^0.6.0

  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.7
  flutter_local_notifications: ^17.1.2
  flutter_mobx: ^2.2.0+2
  flutter_native_splash: ^2.3.5
  # dart run flutter_native_splash:create
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.2.0
  image_cropper: ^5.0.1
  image_picker: ^1.1.1
  json_annotation: ^4.9.0
  mobx: ^2.3.0+1
  multi_dropdown: ^2.1.4
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.3.1
  razorpay_flutter: ^1.3.7
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_pdfviewer: ^26.1.40
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.8
  # dart run build_runner watch --delete-conflicting-outputs
  change_app_package_name: ^1.1.0
  # dart run change_app_package_name:main <com.new.package.name>
  envied_generator: ^0.5.3
  flutter_launcher_icons: ^0.13.1
  # dart run flutter_launcher_icons:main
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mobx_codegen: ^2.6.0+1
  very_good_analysis: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/sg_logo.png"

flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash/sg_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icon/
    - assets/json/doctor_info.json
    - assets/json/members.json
    - assets/json/time_slots.json
    - assets/onboarding/
    - assets/splash/
    - assets/translations/
    - assets/emergency/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf

    - family: AppIcons
      fonts:
        - asset: assets/app_icons/AppIcons.ttf
