name: silver_genie
description: SilverGenie
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  dio_http2_adapter: ^2.3.1+1
  easy_localization: ^3.0.5
  envied: ^0.5.3
  firebase_analytics: ^10.6.3
  firebase_core: ^2.21.0
  firebase_crashlytics: ^3.4.3
  firebase_performance: ^0.9.3+3
  firebase_performance_dio: ^0.6.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.0+2
  flutter_native_splash: ^2.3.5
  # dart run flutter_native_splash:create
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.0
  json_serializable: ^6.7.1
  mobx: ^2.3.0+1
  package_info_plus: ^5.0.1
  pretty_dio_logger: ^1.3.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.8
  # dart run build_runner watch --delete-conflicting-outputs
  change_app_package_name: ^1.1.0
  # dart run change_app_package_name:main <com.new.package.name>
  envied_generator: ^0.5.3
  flutter_launcher_icons: ^0.13.1
  # dart run flutter_launcher_icons:main
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  mobx_codegen: ^2.6.0+1
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash/sg_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icon/
    - assets/onboarding/
    - assets/splash/
    - assets/translations/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf

    - family: AppIcons
      fonts:
        - asset: assets/app_icons/AppIcons.ttf
