class Country {
  const Country(this.name, this.isoCode,);
  final String name;
  final String isoCode;
  
}

List<Country> countries = [
  const Country('Afghanistan', 'AF'),
  const Country('Åland Islands', 'AX'),
  const Country('Albania', 'AL'),
  const Country('Algeria', 'DZ'),
  const Country('American Samoa', 'AS'),
  const Country('Andorra', 'AD'),
  const Country('Angola', 'AO'),
  const Country('Anguilla', 'AI'),
  const Country('Antarctica', 'AQ'),
  const Country('Antigua and Barbuda', 'AG'),
  const Country('Argentina', 'AR'),
  const Country('Armenia', 'AM'),
  const Country('Aruba', 'AW'),
  const Country('Australia', 'AU'),
  const Country('Austria', 'AT'),
  const Country('Azerbaijan', 'AZ'),
  const Country('Bahamas', 'BS'),
  const Country('Bahrain', 'BH'),
  const Country('Bangladesh', 'BD'),
  const Country('Barbados', 'BB'),
  const Country('Belarus', 'BY'),
  const Country('Belgium', 'BE'),
  const Country('Belize', 'BZ'),
  const Country('Benin', 'BJ'),
  const Country('Bermuda', 'BM'),
  const Country('Bhutan', 'BT'),
  const Country('Bolivia', 'BO'),
  const Country('Bosnia and Herzegovina', 'BA'),
  const Country('Botswana', 'BW'),
  const Country('Bouvet Island', 'BV'),
  const Country('Brazil', 'BR'),
  const Country('British Indian Ocean Territory', 'IO'),
  const Country('Brunei Darussalam', 'BN'),
  const Country('Bulgaria', 'BG'),
  const Country('Burkina Faso', 'BF'),
  const Country('Burundi', 'BI'),
  const Country('Cabo Verde', 'CV'),
  const Country('Cambodia', 'KH'),
  const Country('Cameroon', 'CM'),
  const Country('Canada', 'CA'),
  const Country('Cayman Islands', 'KY'),
  const Country('Central African Republic', 'CF'),
  const Country('Chad', 'TD'),
  const Country('Chile', 'CL'),
  const Country('China', 'CN'),
  const Country('Christmas Island', 'CX'),
  const Country('Cocos (Keeling) Islands', 'CC'),
  const Country('Colombia', 'CO'),
  const Country('Comoros', 'KM'),
  const Country('Congo', 'CG'),
  const Country('Congo, Democratic Republic of the', 'CD'),
  const Country('Cook Islands', 'CK'),
  const Country('Costa Rica', 'CR'),
  const Country('Croatia', 'HR'),
  const Country('Cuba', 'CU'),
  const Country('Cyprus', 'CY'),
  const Country('Czechia', 'CZ'),
  const Country('Denmark', 'DK'),
  const Country('Djibouti', 'DJ'),
  const Country('Dominica', 'DM'),
  const Country('Dominican Republic', 'DO'),
  const Country('Ecuador', 'EC'),
  const Country('Egypt', 'EG'),
  const Country('El Salvador', 'SV'),
  const Country('Equatorial Guinea', 'GQ'),
  const Country('Eritrea', 'ER'),
  const Country('Estonia', 'EE'),
  const Country('Eswatini', 'SZ'),
  const Country('Ethiopia', 'ET'),
  const Country('Falkland Islands (Malvinas)', 'FK'),
  const Country('Faroe Islands', 'FO'),
  const Country('Fiji', 'FJ'),
  const Country('Finland', 'FI'),
  const Country('France', 'FR'),
  const Country('French Guiana', 'GF'),
  const Country('French Polynesia', 'PF'),
  const Country('French Southern Territories', 'TF'),
  const Country('Gabon', 'GA'),
  const Country('Gambia', 'GM'),
  const Country('Georgia', 'GE'),
  const Country('Germany', 'DE'),
  const Country('Ghana', 'GH'),
  const Country('Gibraltar', 'GI'),
  const Country('Greece', 'GR'),
  const Country('Greenland', 'GL'),
  const Country('Grenada', 'GD'),
  const Country('Guadeloupe', 'GP'),
  const Country('Guam', 'GU'),
  const Country('Guatemala', 'GT'),
  const Country('Guernsey', 'GG'),
  const Country('Guinea', 'GN'),
  const Country('Guinea-Bissau', 'GW'),
  const Country('Guyana', 'GY'),
  const Country('Haiti', 'HT'),
  const Country('Heard Island and McDonald Islands', 'HM'),
  const Country('Holy See', 'VA'),
  const Country('Honduras', 'HN'),
  const Country('Hong Kong', 'HK'),
  const Country('Hungary', 'HU'),
  const Country('Iceland', 'IS'),
  const Country('India', 'IN'),
  const Country('Indonesia', 'ID'),
  const Country('Iran', 'IR'),
  const Country('Iraq', 'IQ'),
  const Country('Ireland', 'IE'),
  const Country('Isle of Man', 'IM'),
  const Country('Israel', 'IL'),
  const Country('Italy', 'IT'),
  const Country('Jamaica', 'JM'),
  const Country('Japan', 'JP'),
  const Country('Jersey', 'JE'),
  const Country('Jordan', 'JO'),
  const Country('Kazakhstan', 'KZ'),
  const Country('Kenya', 'KE'),
  const Country('Kiribati', 'KI'),
  const Country("Korea (Democratic People's Republic of)", 'KP'),
  const Country('Korea, Republic of', 'KR'),
  const Country('Kuwait', 'KW'),
  const Country('Kyrgyzstan', 'KG'),
  const Country("Lao People's Democratic Republic", 'LA'),
  const Country('Latvia', 'LV'),
  const Country('Lebanon', 'LB'),
  const Country('Lesotho', 'LS'),
  const Country('Liberia', 'LR'),
  const Country('Libya', 'LY'),
  const Country('Liechtenstein', 'LI'),
  const Country('Lithuania', 'LT'),
  const Country('Luxembourg', 'LU'),
  const Country('Macao', 'MO'),
  const Country('Madagascar', 'MG'),
  const Country('Malawi', 'MW'),
  const Country('Malaysia', 'MY'),
  const Country('Maldives', 'MV'),
  const Country('Mali', 'ML'),
  const Country('Malta', 'MT'),
  const Country('Marshall Islands', 'MH'),
  const Country('Martinique', 'MQ'),
  const Country('Mauritania', 'MR'),
  const Country('Mauritius', 'MU'),
  const Country('Mayotte', 'YT'),
  const Country('Mexico', 'MX'),
  const Country('Micronesia (Federated States of)', 'FM'),
  const Country('Moldova, Republic of', 'MD'),
  const Country('Monaco', 'MC'),
  const Country('Mongolia', 'MN'),
  const Country('Montenegro', 'ME'),
  const Country('Montserrat', 'MS'),
  const Country('Morocco', 'MA'),
  const Country('Mozambique', 'MZ'),
  const Country('Myanmar', 'MM'),
  const Country('Namibia', 'NA'),
  const Country('Nauru', 'NR'),
  const Country('Nepal', 'NP'),
  const Country('Netherlands', 'NL'),
  const Country('New Caledonia', 'NC'),
  const Country('New Zealand', 'NZ'),
  const Country('Nicaragua', 'NI'),
  const Country('Niger', 'NE'),
  const Country('Nigeria', 'NG'),
  const Country('Niue', 'NU'),
  const Country('Norfolk Island', 'NF'),
  const Country('North Macedonia', 'MK'),
  const Country('Northern Mariana Islands', 'MP'),
  const Country('Norway', 'NO'),
  const Country('Oman', 'OM'),
  const Country('Pakistan', 'PK'),
  const Country('Palau', 'PW'),
  const Country('Palestine, State of', 'PS'),
  const Country('Panama', 'PA'),
  const Country('Papua New Guinea', 'PG'),
  const Country('Paraguay', 'PY'),
  const Country('Peru', 'PE'),
  const Country('Philippines', 'PH'),
  const Country('Pitcairn', 'PN'),
  const Country('Poland', 'PL'),
  const Country('Portugal', 'PT'),
  const Country('Puerto Rico', 'PR'),
  const Country('Qatar', 'QA'),
  const Country('Réunion', 'RE'),
  const Country('Romania', 'RO'),
  const Country('Russian Federation', 'RU'),
  const Country('Rwanda', 'RW'),
  const Country('Saint Barthélemy', 'BL'),
  const Country('Saint Helena, Ascension and Tristan da Cunha', 'SH'),
  const Country('Saint Kitts and Nevis', 'KN'),
  const Country('Saint Lucia', 'LC'),
  const Country('Saint Martin (French part)', 'MF'),
  const Country('Saint Pierre and Miquelon', 'PM'),
  const Country('Saint Vincent and the Grenadines', 'VC'),
  const Country('Samoa', 'WS'),
  const Country('San Marino', 'SM'),
  const Country('Sao Tome and Principe', 'ST'),
  const Country('Saudi Arabia', 'SA'),
  const Country('Senegal', 'SN'),
  const Country('Serbia', 'RS'),
  const Country('Seychelles', 'SC'),
  const Country('Sierra Leone', 'SL'),
  const Country('Singapore', 'SG'),
  const Country('Sint Maarten (Dutch part)', 'SX'),
  const Country('Slovakia', 'SK'),
  const Country('Slovenia', 'SI'),
  const Country('Solomon Islands', 'SB'),
  const Country('Somalia', 'SO'),
  const Country('South Africa', 'ZA'),
  const Country('South Georgia and the South Sandwich Islands', 'GS'),
  const Country('South Sudan', 'SS'),
  const Country('Spain', 'ES'),
  const Country('Sri Lanka', 'LK'),
  const Country('Sudan', 'SD'),
  const Country('Suriname', 'SR'),
  const Country('Svalbard and Jan Mayen', 'SJ'),
  const Country('Sweden', 'SE'),
  const Country('Switzerland', 'CH'),
  const Country('Syrian Arab Republic', 'SY'),
  const Country('Taiwan', 'TW'),
  const Country('Tajikistan', 'TJ'),
  const Country('Tanzania, United Republic of', 'TZ'),
  const Country('Thailand', 'TH'),
  const Country('Timor-Leste', 'TL'),
  const Country('Togo', 'TG'),
  const Country('Tokelau', 'TK'),
  const Country('Tonga', 'TO'),
  const Country('Trinidad and Tobago', 'TT'),
  const Country('Tunisia', 'TN'),
  const Country('Turkey', 'TR'),
  const Country('Turkmenistan', 'TM'),
  const Country('Turks and Caicos Islands', 'TC'),
  const Country('Tuvalu', 'TV'),
  const Country('Uganda', 'UG'),
  const Country('Ukraine', 'UA'),
  const Country('United Arab Emirates', 'AE'),
  const Country('United Kingdom of Great Britain and Northern Ireland', 'GB'),
  const Country('United States of America', 'US'),
  const Country('Uruguay', 'UY'),
  const Country('Uzbekistan', 'UZ'),
  const Country('Vanuatu', 'VU'),
  const Country('Venezuela', 'VE'),
  const Country('Viet Nam', 'VN'),
  const Country('Virgin Islands (British)', 'VG'),
  const Country('Virgin Islands (U.S.)', 'VI'),
  const Country('Wallis and Futuna', 'WF'),
  const Country('Western Sahara', 'EH'),
  const Country('Yemen', 'YE'),
  const Country('Zambia', 'ZM'),
  const Country('Zimbabwe', 'ZW'),
];

const Map<String, int> countryMobileDigitCount = {
  'AF': 9, 'AX': 7, 'AL': 9, 'DZ': 9, 'AS': 10, 'AD': 9, 'AO': 9, 'AI': 10,
  'AQ': 6, 'AG': 10, 'AR': 10, 'AM': 8, 'AW': 7, 'AU': 9, 'AT': 9, 'AZ': 9,
  'BS': 10, 'BH': 8, 'BD': 10, 'BB': 10, 'BY': 9, 'BE': 9, 'BZ': 7, 'BJ': 8,
  'BM': 10, 'BT': 8, 'BO': 8, 'BA': 8, 'BW': 8, 'BV': 9, 'BR': 11, 'IO': 7,
  'BN': 7, 'BG': 9, 'BF': 8, 'BI': 8, 'CV': 7, 'KH': 9, 'CM': 9, 'CA': 10,
  'KY': 10, 'CF': 8, 'TD': 8, 'CL': 9, 'CN': 11, 'CX': 6, 'CC': 6, 'CO': 10,
  'KM': 7, 'CG': 9, 'CD': 9, 'CK': 5, 'CR': 8, 'HR': 9, 'CU': 8, 'CY': 8,
  'CZ': 9, 'DK': 8, 'DJ': 8, 'DM': 10, 'DO': 10, 'EC': 9, 'EG': 10, 'SV': 8,
  'GQ': 9, 'ER': 7, 'EE': 9, 'SZ': 8, 'ET': 9, 'FK': 9, 'FO': 9, 'FJ': 7,
  'FI': 9, 'FR': 9, 'GF': 9, 'PF': 6, 'TF': 9, 'GA': 8, 'GM': 7, 'GE': 9,
  'DE': 10, 'GH': 9, 'GI': 8, 'GR': 10, 'GL': 6, 'GD': 10, 'GP': 9, 'GU': 10,
  'GT': 8, 'GG': 6, 'GN': 9, 'GW': 7, 'GY': 7, 'HT': 8, 'HM': 7, 'VA': 9,
  'HN': 8, 'HK': 8, 'HU': 9, 'IS': 7, 'IN': 10, 'ID': 10, 'IR': 10, 'IQ': 10,
  'IE': 9, 'IM': 9, 'IL': 10, 'IT': 10, 'JM': 10, 'JP': 10, 'JE': 6, 'JO': 9,
  'KZ': 10, 'KE': 10, 'KI': 7, 'KP': 10, 'KR': 10, 'KW': 8, 'KG': 9, 'LA': 9,
  'LV': 8, 'LB': 8, 'LS': 8, 'LR': 7, 'LY': 9, 'LI': 9, 'LT': 8, 'LU': 9,
  'MO': 8, 'MG': 9, 'MW': 8, 'MY': 10, 'MV': 7, 'ML': 8, 'MT': 8, 'MH': 7,
  'MQ': 9, 'MR': 8, 'MU': 8, 'YT': 9, 'MX': 10, 'FM': 7, 'MD': 8, 'MC': 8,
  'MN': 8, 'ME': 8, 'MS': 10, 'MA': 9, 'MZ': 9, 'MM': 9, 'NA': 9, 'NR': 7,
  'NP': 10, 'NL': 9, 'NC': 6, 'NZ': 9, 'NI': 8, 'NE': 8, 'NG': 10, 'NU': 4,
  'NF': 6, 'MK': 8, 'MP': 10, 'NO': 8, 'OM': 8, 'PK': 10, 'PW': 7, 'PS': 9,
  'PA': 8, 'PG': 8, 'PY': 9, 'PE': 9, 'PH': 10, 'PN': 4, 'PL': 9, 'PT': 9,
  'PR': 10, 'QA': 8, 'RE': 9, 'RO': 10, 'RU': 10, 'RW': 9, 'BL': 9, 'SH': 7,
  'KN': 10, 'LC': 10, 'MF': 9, 'PM': 6, 'VC': 10, 'WS': 7, 'SM': 9, 'ST': 7,
  'SA': 9, 'SN': 9, 'RS': 8, 'SC': 7, 'SL': 8, 'SG': 8, 'SX': 10, 'SK': 9,
  'SI': 8, 'SB': 7, 'SO': 8, 'ZA': 10, 'GS': 0, 'SS': 9, 'ES': 9, 'LK': 9,
  'SD': 9, 'SR': 7, 'SJ': 0, 'SE': 9, 'CH': 9, 'SY': 9, 'TW': 9, 'TJ': 9,
  'TZ': 9, 'TH': 9, 'TL': 8, 'TG': 8, 'TK': 5, 'TO': 5, 'TT': 10, 'TN': 8,
  'TR': 10, 'TM': 8, 'TC': 10, 'TV': 5, 'UG': 9, 'UA': 9, 'AE': 9, 'GB': 10,
  'US': 10, 'UY': 8, 'UZ': 9, 'VU': 7, 'VE': 10, 'VN': 9, 'EH': 9, 'YE': 9,
  'ZM': 9, 'ZW': 9,
};