class Country {
  final String name;
  final String flagEmoji;
  final String phoneCode;
  final String isoCode;

  const Country({
    required this.name,
    required this.isoCode,
    required this.flagEmoji,
    required this.phoneCode,
  });
}

class CountryApi {
  static Country getCountryByIsoCode(String isoCode) => countries.firstWhere((element) => element.isoCode == isoCode,);
}

const List<Country> countries = [
  Country(
      name: 'Afghanistan', isoCode: 'AF', flagEmoji: '🇦🇫', phoneCode: '+93'),
  Country(name: 'Albania', isoCode: 'AL', flagEmoji: '🇦🇱', phoneCode: '+355'),
  Country(name: 'Algeria', isoCode: 'DZ', flagEmoji: '🇩🇿', phoneCode: '+213'),
  Country(name: 'Andorra', isoCode: 'AD', flagEmoji: '🇦🇩', phoneCode: '+376'),
  Country(name: 'Angola', isoCode: 'AO', flagEmoji: '🇦🇴', phoneCode: '+244'),
  Country(
      name: 'Antigua and Barbuda',
      isoCode: 'AG',
      flagEmoji: '🇦🇬',
      phoneCode: '+1-268'),
  Country(
      name: 'Argentina', isoCode: 'AR', flagEmoji: '🇦🇷', phoneCode: '+54'),
  Country(name: 'Armenia', isoCode: 'AM', flagEmoji: '🇦🇲', phoneCode: '+374'),
  Country(
      name: 'Australia', isoCode: 'AU', flagEmoji: '🇦🇺', phoneCode: '+61'),
  Country(name: 'Austria', isoCode: 'AT', flagEmoji: '🇦🇹', phoneCode: '+43'),
  Country(name: 'Åland Islands', isoCode: 'AX', flagEmoji: '🇦🇽', phoneCode: '+358'),
  Country(
      name: 'Azerbaijan', isoCode: 'AZ', flagEmoji: '🇦🇿', phoneCode: '+994'),
  Country(
      name: 'Bahamas', isoCode: 'BS', flagEmoji: '🇧🇸', phoneCode: '+1-242'),
  Country(name: 'Bahrain', isoCode: 'BH', flagEmoji: '🇧🇭', phoneCode: '+973'),
  Country(
      name: 'Bangladesh', isoCode: 'BD', flagEmoji: '🇧🇩', phoneCode: '+880'),
  Country(
      name: 'Barbados', isoCode: 'BB', flagEmoji: '🇧🇧', phoneCode: '+1-246'),
  Country(name: 'Belarus', isoCode: 'BY', flagEmoji: '🇧🇾', phoneCode: '+375'),
  Country(name: 'Belgium', isoCode: 'BE', flagEmoji: '🇧🇪', phoneCode: '+32'),
  Country(name: 'Belize', isoCode: 'BZ', flagEmoji: '🇧🇿', phoneCode: '+501'),
  Country(name: 'Benin', isoCode: 'BJ', flagEmoji: '🇧🇯', phoneCode: '+229'),
  Country(name: 'Bhutan', isoCode: 'BT', flagEmoji: '🇧🇹', phoneCode: '+975'),
  Country(
      name: 'Bolivia (Plurinational State of)',
      isoCode: 'BO',
      flagEmoji: '🇧🇴',
      phoneCode: '+591'),
  Country(
      name: 'Bosnia and Herzegovina',
      isoCode: 'BA',
      flagEmoji: '🇧🇦',
      phoneCode: '+387'),
  Country(
      name: 'Botswana', isoCode: 'BW', flagEmoji: '🇧🇼', phoneCode: '+267'),
  Country(name: 'Brazil', isoCode: 'BR', flagEmoji: '🇧🇷', phoneCode: '+55'),
  Country(
      name: 'Brunei Darussalam',
      isoCode: 'BN',
      flagEmoji: '🇧🇳',
      phoneCode: '+673'),
  Country(
      name: 'Bulgaria', isoCode: 'BG', flagEmoji: '🇧🇬', phoneCode: '+359'),
  Country(
      name: 'Burkina Faso',
      isoCode: 'BF',
      flagEmoji: '🇧🇫',
      phoneCode: '+226'),
  Country(name: 'Burundi', isoCode: 'BI', flagEmoji: '🇧🇮', phoneCode: '+257'),
  Country(
      name: 'Cabo Verde', isoCode: 'CV', flagEmoji: '🇨🇻', phoneCode: '+238'),
  Country(
      name: 'Cambodia', isoCode: 'KH', flagEmoji: '🇰🇭', phoneCode: '+855'),
  Country(
      name: 'Cameroon', isoCode: 'CM', flagEmoji: '🇨🇲', phoneCode: '+237'),
  Country(name: 'Canada', isoCode: 'CA', flagEmoji: '🇨🇦', phoneCode: '+1'),
  Country(
      name: 'Central African Republic',
      isoCode: 'CF',
      flagEmoji: '🇨🇫',
      phoneCode: '+236'),
  Country(name: 'Chad', isoCode: 'TD', flagEmoji: '🇹🇩', phoneCode: '+235'),
  Country(name: 'Chile', isoCode: 'CL', flagEmoji: '🇨🇱', phoneCode: '+56'),
  Country(name: 'China', isoCode: 'CN', flagEmoji: '🇨🇳', phoneCode: '+86'),
  Country(name: 'Colombia', isoCode: 'CO', flagEmoji: '🇨🇴', phoneCode: '+57'),
  Country(name: 'Comoros', isoCode: 'KM', flagEmoji: '🇰🇲', phoneCode: '+269'),
  Country(name: 'Congo', isoCode: 'CG', flagEmoji: '🇨🇬', phoneCode: '+242'),
  Country(
      name: 'Congo (Democratic Republic of the)',
      isoCode: 'CD',
      flagEmoji: '🇨🇩',
      phoneCode: '+243'),
  Country(
      name: 'Cook Islands',
      isoCode: 'CK',
      flagEmoji: '🇨🇰',
      phoneCode: '+682'),
  Country(
      name: 'Costa Rica', isoCode: 'CR', flagEmoji: '🇨🇷', phoneCode: '+506'),
  Country(name: 'Croatia', isoCode: 'HR', flagEmoji: '🇭🇷', phoneCode: '+385'),
  Country(name: 'Cuba', isoCode: 'CU', flagEmoji: '🇨🇺', phoneCode: '+53'),
  Country(name: 'Curaçao', isoCode: 'CW', flagEmoji: '🇨🇼', phoneCode: '+599'),
  Country(name: 'Cyprus', isoCode: 'CY', flagEmoji: '🇨🇾', phoneCode: '+357'),
  Country(name: 'Czechia', isoCode: 'CZ', flagEmoji: '🇨🇿', phoneCode: '+420'),
  Country(name: 'Denmark', isoCode: 'DK', flagEmoji: '🇩🇰', phoneCode: '+45'),
  Country(
      name: 'Djibouti', isoCode: 'DJ', flagEmoji: '🇩🇯', phoneCode: '+253'),
  Country(
      name: 'Dominica', isoCode: 'DM', flagEmoji: '🇩🇲', phoneCode: '+1-767'),
  Country(
      name: 'Dominican Republic',
      isoCode: 'DO',
      flagEmoji: '🇩🇴',
      phoneCode: '+1-809'),
  Country(name: 'Ecuador', isoCode: 'EC', flagEmoji: '🇪🇨', phoneCode: '+593'),
  Country(name: 'Egypt', isoCode: 'EG', flagEmoji: '🇪🇬', phoneCode: '+20'),
  Country(
      name: 'El Salvador', isoCode: 'SV', flagEmoji: '🇸🇻', phoneCode: '+503'),
  Country(
      name: 'Equatorial Guinea',
      isoCode: 'GQ',
      flagEmoji: '🇬🇶',
      phoneCode: '+240'),
  Country(name: 'Eritrea', isoCode: 'ER', flagEmoji: '🇪🇷', phoneCode: '+291'),
  Country(name: 'Estonia', isoCode: 'EE', flagEmoji: '🇪🇪', phoneCode: '+372'),
  Country(
      name: 'Eswatini', isoCode: 'SZ', flagEmoji: '🇸🇿', phoneCode: '+268'),
  Country(
      name: 'Ethiopia', isoCode: 'ET', flagEmoji: '🇪🇹', phoneCode: '+251'),
  Country(name: 'Fiji', isoCode: 'FJ', flagEmoji: '🇫🇯', phoneCode: '+679'),
  Country(name: 'Finland', isoCode: 'FI', flagEmoji: '🇫🇮', phoneCode: '+358'),
  Country(name: 'France', isoCode: 'FR', flagEmoji: '🇫🇷', phoneCode: '+33'),
  Country(name: 'Gabon', isoCode: 'GA', flagEmoji: '🇬🇦', phoneCode: '+241'),
  Country(name: 'Gambia', isoCode: 'GM', flagEmoji: '🇲🇷', phoneCode: '+220'),
  Country(name: 'Georgia', isoCode: 'GE', flagEmoji: '🇬🇪', phoneCode: '+995'),
  Country(name: 'Germany', isoCode: 'DE', flagEmoji: '🇩🇪', phoneCode: '+49'),
  Country(name: 'Ghana', isoCode: 'GH', flagEmoji: '🇬🇭', phoneCode: '+233'),
  Country(name: 'Greece', isoCode: 'GR', flagEmoji: '🇬🇷', phoneCode: '+30'),
  Country(
      name: 'Grenada', isoCode: 'GD', flagEmoji: '🇬🇩', phoneCode: '+1-473'),
  Country(
      name: 'Guatemala', isoCode: 'GT', flagEmoji: '🇵🇪', phoneCode: '+502'),
  Country(name: 'Guinea', isoCode: 'GN', flagEmoji: '🇬🇳', phoneCode: '+224'),
  Country(
      name: 'Guinea-Bissau',
      isoCode: 'GW',
      flagEmoji: '🇬🇼',
      phoneCode: '+245'),
  Country(name: 'Guyana', isoCode: 'GY', flagEmoji: '🇬🇾', phoneCode: '+592'),
  Country(name: 'Haiti', isoCode: 'HT', flagEmoji: '🇭🇹', phoneCode: '+509'),
  Country(
      name: 'Honduras', isoCode: 'HN', flagEmoji: '🇭🇳', phoneCode: '+504'),
  Country(name: 'Hungary', isoCode: 'HU', flagEmoji: '🇭🇺', phoneCode: '+36'),
  Country(name: 'Iceland', isoCode: 'IS', flagEmoji: '🇮🇸', phoneCode: '+354'),
  Country(name: 'India', isoCode: 'IN', flagEmoji: '🇮🇳', phoneCode: '+91'),
  Country(
      name: 'Indonesia', isoCode: 'ID', flagEmoji: '🇮🇩', phoneCode: '+62'),
  Country(
      name: 'Iran (Islamic Republic of)',
      isoCode: 'IR',
      flagEmoji: '🇮🇷',
      phoneCode: '+98'),
  Country(name: 'Iraq', isoCode: 'IQ', flagEmoji: '🇮🇶', phoneCode: '+964'),
  Country(name: 'Ireland', isoCode: 'IE', flagEmoji: '🇮🇪', phoneCode: '+353'),
  Country(name: 'Israel', isoCode: 'IL', flagEmoji: '🇮🇱', phoneCode: '+972'),
  Country(name: 'Italy', isoCode: 'IT', flagEmoji: '🇮🇹', phoneCode: '+39'),
  Country(
      name: 'Jamaica', isoCode: 'JM', flagEmoji: '🇯🇲', phoneCode: '+1-876'),
  Country(name: 'Japan', isoCode: 'JP', flagEmoji: '🇯🇵', phoneCode: '+81'),
  Country(name: 'Jordan', isoCode: 'JO', flagEmoji: '🇯🇴', phoneCode: '+962'),
  Country(
      name: 'Kazakhstan', isoCode: 'KZ', flagEmoji: '🇰🇿', phoneCode: '+7'),
  Country(name: 'Kenya', isoCode: 'KE', flagEmoji: '🇰🇪', phoneCode: '+254'),
  Country(
      name: 'Kiribati', isoCode: 'KI', flagEmoji: '🇰🇮', phoneCode: '+686'),
  Country(
      name: 'Korea (Democratic People\'s Republic of)',
      isoCode: 'KP',
      flagEmoji: '🇰🇵',
      phoneCode: '+850'),
  Country(
      name: 'Korea, Republic of',
      isoCode: 'KR',
      flagEmoji: '🇰🇷',
      phoneCode: '+82'),
  Country(name: 'Kuwait', isoCode: 'KW', flagEmoji: '🇰🇼', phoneCode: '+965'),
  Country(
      name: 'Kyrgyzstan', isoCode: 'KG', flagEmoji: '🇰🇬', phoneCode: '+996'),
  Country(
      name: 'Lao People\'s Democratic Republic',
      isoCode: 'LA',
      flagEmoji: '🇱🇦',
      phoneCode: '+856'),
  Country(name: 'Latvia', isoCode: 'LV', flagEmoji: '🇱🇻', phoneCode: '+371'),
  Country(name: 'Lebanon', isoCode: 'LB', flagEmoji: '🇱🇧', phoneCode: '+961'),
  Country(name: 'Lesotho', isoCode: 'LS', flagEmoji: '🇱🇸', phoneCode: '+266'),
  Country(name: 'Liberia', isoCode: 'LR', flagEmoji: '🇱🇸', phoneCode: '+231'),
  Country(name: 'Libya', isoCode: 'LY', flagEmoji: '🇱🇾', phoneCode: '+218'),
  Country(
      name: 'Liechtenstein',
      isoCode: 'LI',
      flagEmoji: '🇱🇮',
      phoneCode: '+423'),
  Country(
      name: 'Lithuania', isoCode: 'LT', flagEmoji: '🇱🇹', phoneCode: '+370'),
  Country(
      name: 'Luxembourg', isoCode: 'LU', flagEmoji: '🇱🇺', phoneCode: '+352'),
  Country(
      name: 'Madagascar', isoCode: 'MG', flagEmoji: '🇲🇬', phoneCode: '+261'),
  Country(name: 'Malawi', isoCode: 'MW', flagEmoji: '🇲🇼', phoneCode: '+265'),
  Country(name: 'Malaysia', isoCode: 'MY', flagEmoji: '🇲🇾', phoneCode: '+60'),
  Country(
      name: 'Maldives', isoCode: 'MV', flagEmoji: '🇲🇻', phoneCode: '+960'),
  Country(name: 'Mali', isoCode: 'ML', flagEmoji: '🇲🇱', phoneCode: '+223'),
  Country(name: 'Malta', isoCode: 'MT', flagEmoji: '🇲🇹', phoneCode: '+356'),
  Country(
      name: 'Marshall Islands',
      isoCode: 'MH',
      flagEmoji: '🇲🇭',
      phoneCode: '+692'),
  Country(
      name: 'Mauritania', isoCode: 'MR', flagEmoji: '🇲🇷', phoneCode: '+222'),
  Country(
      name: 'Mauritius', isoCode: 'MU', flagEmoji: '🇲🇺', phoneCode: '+230'),
  Country(name: 'Mexico', isoCode: 'MX', flagEmoji: '🇲🇽', phoneCode: '+52'),
  Country(
      name: 'Micronesia (Federated States of)',
      isoCode: 'FM',
      flagEmoji: '🇲🇭',
      phoneCode: '+691'),
  Country(
      name: 'Moldova (Republic of)',
      isoCode: 'MD',
      flagEmoji: '🇲🇩',
      phoneCode: '+373'),
  Country(name: 'Monaco', isoCode: 'MC', flagEmoji: '🇲🇨', phoneCode: '+377'),
  Country(
      name: 'Mongolia', isoCode: 'MN', flagEmoji: '🇲🇳', phoneCode: '+976'),
  Country(
      name: 'Montenegro', isoCode: 'ME', flagEmoji: '🇲🇪', phoneCode: '+382'),
  Country(name: 'Morocco', isoCode: 'MA', flagEmoji: '🇲🇦', phoneCode: '+212'),
  Country(
      name: 'Mozambique', isoCode: 'MZ', flagEmoji: '🇲🇿', phoneCode: '+258'),
  Country(name: 'Myanmar', isoCode: 'MM', flagEmoji: '🇲🇲', phoneCode: '+95'),
  Country(name: 'Namibia', isoCode: 'NA', flagEmoji: '🇳🇦', phoneCode: '+264'),
  Country(name: 'Nauru', isoCode: 'NR', flagEmoji: '🇳🇷', phoneCode: '+674'),
  Country(name: 'Nepal', isoCode: 'NP', flagEmoji: '🇳🇵', phoneCode: '+977'),
  Country(
      name: 'Netherlands', isoCode: 'NL', flagEmoji: '🇳🇱', phoneCode: '+31'),
  Country(
      name: 'New Caledonia',
      isoCode: 'NC',
      flagEmoji: '🇳🇨',
      phoneCode: '+687'),
  Country(
      name: 'New Zealand', isoCode: 'NZ', flagEmoji: '🇳🇿', phoneCode: '+64'),
  Country(
      name: 'Nicaragua', isoCode: 'NI', flagEmoji: '🇳🇮', phoneCode: '+505'),
  Country(name: 'Niger', isoCode: 'NE', flagEmoji: '🇳🇪', phoneCode: '+227'),
  Country(name: 'Nigeria', isoCode: 'NG', flagEmoji: '🇳🇬', phoneCode: '+234'),
  Country(name: 'Niue', isoCode: 'NU', flagEmoji: '🇳🇺', phoneCode: '+683'),
  Country(
      name: 'Norfolk Island',
      isoCode: 'NF',
      flagEmoji: '🇳🇫',
      phoneCode: '+672'),
  Country(
      name: 'North Macedonia',
      isoCode: 'MK',
      flagEmoji: '🇲🇰',
      phoneCode: '+389'),
  Country(
      name: 'Northern Mariana Islands',
      isoCode: 'MP',
      flagEmoji: '🇲🇵',
      phoneCode: '+1-670'),
  Country(name: 'Norway', isoCode: 'NO', flagEmoji: '🇳🇴', phoneCode: '+47'),
  Country(name: 'Oman', isoCode: 'OM', flagEmoji: '🇴🇲', phoneCode: '+968'),
  Country(name: 'Pakistan', isoCode: 'PK', flagEmoji: '🇵🇰', phoneCode: '+92'),
  Country(name: 'Palau', isoCode: 'PW', flagEmoji: '🇵🇼', phoneCode: '+680'),
  Country(name: 'Panama', isoCode: 'PA', flagEmoji: '🇵🇦', phoneCode: '+507'),
  Country(
      name: 'Papua New Guinea',
      isoCode: 'PG',
      flagEmoji: '🇵🇬',
      phoneCode: '+675'),
  Country(
      name: 'Paraguay', isoCode: 'PY', flagEmoji: '🇵🇾', phoneCode: '+595'),
  Country(name: 'Peru', isoCode: 'PE', flagEmoji: '🇵🇪', phoneCode: '+51'),
  Country(
      name: 'Philippines', isoCode: 'PH', flagEmoji: '🇵🇭', phoneCode: '+63'),
  Country(name: 'Pitcairn', isoCode: 'PN', flagEmoji: '🇵🇳', phoneCode: '+64'),
  Country(name: 'Poland', isoCode: 'PL', flagEmoji: '🇵🇱', phoneCode: '+48'),
  Country(
      name: 'Portugal', isoCode: 'PT', flagEmoji: '🇵🇹', phoneCode: '+351'),
  Country(
      name: 'Puerto Rico',
      isoCode: 'PR',
      flagEmoji: '🇵🇷',
      phoneCode: '+1-787'),
  Country(name: 'Qatar', isoCode: 'QA', flagEmoji: '🇶🇦', phoneCode: '+974'),
  Country(name: 'Romania', isoCode: 'RO', flagEmoji: '🇷🇴', phoneCode: '+40'),
  Country(
      name: 'Russian Federation',
      isoCode: 'RU',
      flagEmoji: '🇷🇺',
      phoneCode: '+7'),
  Country(name: 'Rwanda', isoCode: 'RW', flagEmoji: '🇷🇼', phoneCode: '+250'),
  Country(name: 'Réunion', isoCode: 'RE', flagEmoji: '🇷🇪', phoneCode: '+262'),
  Country(
      name: 'Saint Kitts and Nevis',
      isoCode: 'KN',
      flagEmoji: '🇰🇳',
      phoneCode: '+1-869'),
  Country(
      name: 'Saint Lucia',
      isoCode: 'LC',
      flagEmoji: '🇱🇨',
      phoneCode: '+1-758'),
  Country(
      name: 'Saint Vincent and the Grenadines',
      isoCode: 'VC',
      flagEmoji: '🇻🇨',
      phoneCode: '+1-784'),
  Country(name: 'Samoa', isoCode: 'WS', flagEmoji: '🇼🇸', phoneCode: '+685'),
  Country(
      name: 'San Marino', isoCode: 'SM', flagEmoji: '🇸🇲', phoneCode: '+378'),
  Country(
      name: 'Sao Tome and Principe',
      isoCode: 'ST',
      flagEmoji: '🇸🇹',
      phoneCode: '+239'),
  Country(
      name: 'Saudi Arabia',
      isoCode: 'SA',
      flagEmoji: '🇸🇦',
      phoneCode: '+966'),
  Country(name: 'Senegal', isoCode: 'SN', flagEmoji: '🇸🇳', phoneCode: '+221'),
  Country(name: 'Serbia', isoCode: 'RS', flagEmoji: '🇷🇸', phoneCode: '+381'),
  Country(
      name: 'Seychelles', isoCode: 'SC', flagEmoji: '🇸🇨', phoneCode: '+248'),
  Country(
      name: 'Sierra Leone',
      isoCode: 'SL',
      flagEmoji: '🇸🇱',
      phoneCode: '+232'),
  Country(
      name: 'Singapore', isoCode: 'SG', flagEmoji: '🇸🇬', phoneCode: '+65'),
  Country(
      name: 'Sint Maarten (Dutch part)',
      isoCode: 'SX',
      flagEmoji: '🇸🇽',
      phoneCode: '+1-721'),
  Country(
      name: 'Slovakia', isoCode: 'SK', flagEmoji: '🇸🇰', phoneCode: '+421'),
  Country(
      name: 'Slovenia', isoCode: 'SI', flagEmoji: '🇸🇮', phoneCode: '+386'),
  Country(
      name: 'Solomon Islands',
      isoCode: 'SB',
      flagEmoji: '🇸🇧',
      phoneCode: '+677'),
  Country(name: 'Somalia', isoCode: 'SO', flagEmoji: '🇸🇴', phoneCode: '+252'),
  Country(
      name: 'South Africa', isoCode: 'ZA', flagEmoji: '🇿🇦', phoneCode: '+27'),
  Country(
      name: 'South Sudan', isoCode: 'SS', flagEmoji: '🇸🇸', phoneCode: '+211'),
  Country(name: 'Spain', isoCode: 'ES', flagEmoji: '🇪🇸', phoneCode: '+34'),
  Country(
      name: 'Sri Lanka', isoCode: 'LK', flagEmoji: '🇱🇰', phoneCode: '+94'),
  Country(name: 'Sudan', isoCode: 'SD', flagEmoji: '🇸🇩', phoneCode: '+249'),
  Country(
      name: 'Suriname', isoCode: 'SR', flagEmoji: '🇸🇷', phoneCode: '+597'),
  Country(name: 'Sweden', isoCode: 'SE', flagEmoji: '🇸🇪', phoneCode: '+46'),
  Country(
      name: 'Switzerland', isoCode: 'CH', flagEmoji: '🇨🇭', phoneCode: '+41'),
  Country(
      name: 'Syrian Arab Republic',
      isoCode: 'SY',
      flagEmoji: '🇸🇾',
      phoneCode: '+963'),
  Country(
      name: 'Taiwan, Province of China',
      isoCode: 'TW',
      flagEmoji: '🇹🇼',
      phoneCode: '+886'),
  Country(
      name: 'Tajikistan', isoCode: 'TJ', flagEmoji: '🇹🇯', phoneCode: '+992'),
  Country(
      name: 'Tanzania, United Republic of',
      isoCode: 'TZ',
      flagEmoji: '🇹🇿',
      phoneCode: '+255'),
  Country(name: 'Thailand', isoCode: 'TH', flagEmoji: '🇹🇭', phoneCode: '+66'),
  Country(
      name: 'Timor-Leste', isoCode: 'TL', flagEmoji: '🇹🇱', phoneCode: '+670'),
  Country(name: 'Togo', isoCode: 'TG', flagEmoji: '🇹🇬', phoneCode: '+228'),
  Country(name: 'Tokelau', isoCode: 'TK', flagEmoji: '🇹🇰', phoneCode: '+690'),
  Country(name: 'Tonga', isoCode: 'TO', flagEmoji: '🇹🇴', phoneCode: '+676'),
  Country(
      name: 'Trinidad and Tobago',
      isoCode: 'TT',
      flagEmoji: '🇹🇹',
      phoneCode: '+1-868'),
  Country(name: 'Tunisia', isoCode: 'TN', flagEmoji: '🇹🇳', phoneCode: '+216'),
  Country(name: 'Turkey', isoCode: 'TR', flagEmoji: '🇹🇷', phoneCode: '+90'),
  Country(
      name: 'Turkmenistan',
      isoCode: 'TM',
      flagEmoji: '🇹🇲',
      phoneCode: '+993'),
  Country(name: 'Tuvalu', isoCode: 'TV', flagEmoji: '🇹🇻', phoneCode: '+688'),
  Country(name: 'Uganda', isoCode: 'UG', flagEmoji: '🇺🇬', phoneCode: '+256'),
  Country(name: 'Ukraine', isoCode: 'UA', flagEmoji: '🇺🇦', phoneCode: '+380'),
  Country(
      name: 'United Arab Emirates',
      isoCode: 'AE',
      flagEmoji: '🇦🇪',
      phoneCode: '+971'),
  Country(
      name: 'United Kingdom of Great Britain and Northern Ireland',
      isoCode: 'GB',
      flagEmoji: '🇬🇧',
      phoneCode: '+44'),
  Country(
      name: 'United States of America',
      isoCode: 'US',
      flagEmoji: '🇺🇸',
      phoneCode: '+1'),
  Country(name: 'Uruguay', isoCode: 'UY', flagEmoji: '🇺🇾', phoneCode: '+598'),
  Country(
      name: 'Uzbekistan', isoCode: 'UZ', flagEmoji: '🇺🇿', phoneCode: '+998'),
  Country(name: 'Vanuatu', isoCode: 'VU', flagEmoji: '🇻🇺', phoneCode: '+678'),
  Country(
      name: 'Venezuela (Bolivarian Republic of)',
      isoCode: 'VE',
      flagEmoji: '🇻🇪',
      phoneCode: '+58'),
  Country(name: 'Viet Nam', isoCode: 'VN', flagEmoji: '🇻🇳', phoneCode: '+84'),
  Country(
      name: 'Western Sahara',
      isoCode: 'EH',
      flagEmoji: '🇪🇭',
      phoneCode: '+212'),
  Country(name: 'Yemen', isoCode: 'YE', flagEmoji: '🇾🇪', phoneCode: '+967'),
  Country(name: 'Zambia', isoCode: 'ZM', flagEmoji: '🇿🇲', phoneCode: '+260'),
  Country(
      name: 'Zimbabwe', isoCode: 'ZW', flagEmoji: '🇿🇼', phoneCode: '+263'),
];

const Map<String, int> countryMobileDigitCount = {
  'AF': 9,
  'AX': 7,
  'AL': 9,
  'DZ': 9,
  'AS': 10,
  'AD': 9,
  'AO': 9,
  'AI': 10,
  'AQ': 6,
  'AG': 10,
  'AR': 10,
  'AM': 8,
  'AW': 7,
  'AU': 9,
  'AT': 9,
  'AZ': 9,
  'BS': 10,
  'BH': 8,
  'BD': 10,
  'BB': 10,
  'BY': 9,
  'BE': 9,
  'BZ': 7,
  'BJ': 8,
  'BM': 10,
  'BT': 8,
  'BO': 8,
  'BA': 8,
  'BW': 8,
  'BV': 9,
  'BR': 11,
  'IO': 7,
  'BN': 7,
  'BG': 9,
  'BF': 8,
  'BI': 8,
  'CV': 7,
  'KH': 9,
  'CM': 9,
  'CA': 10,
  'KY': 10,
  'CF': 8,
  'TD': 8,
  'CL': 9,
  'CN': 11,
  'CX': 6,
  'CC': 6,
  'CO': 10,
  'KM': 7,
  'CG': 9,
  'CD': 9,
  'CK': 5,
  'CR': 8,
  'HR': 9,
  'CU': 8,
  'CY': 8,
  'CZ': 9,
  'DK': 8,
  'DJ': 8,
  'DM': 10,
  'DO': 10,
  'EC': 9,
  'EG': 10,
  'SV': 8,
  'GQ': 9,
  'ER': 7,
  'EE': 9,
  'SZ': 8,
  'ET': 9,
  'FK': 9,
  'FO': 9,
  'FJ': 7,
  'FI': 9,
  'FR': 9,
  'GF': 9,
  'PF': 6,
  'TF': 9,
  'GA': 8,
  'GM': 7,
  'GE': 9,
  'DE': 10,
  'GH': 9,
  'GI': 8,
  'GR': 10,
  'GL': 6,
  'GD': 10,
  'GP': 9,
  'GU': 10,
  'GT': 8,
  'GG': 6,
  'GN': 9,
  'GW': 7,
  'GY': 7,
  'HT': 8,
  'HM': 7,
  'VA': 9,
  'HN': 8,
  'HK': 8,
  'HU': 9,
  'IS': 7,
  'IN': 10,
  'ID': 10,
  'IR': 10,
  'IQ': 10,
  'IE': 9,
  'IM': 9,
  'IL': 10,
  'IT': 10,
  'JM': 10,
  'JP': 10,
  'JE': 6,
  'JO': 9,
  'KZ': 10,
  'KE': 10,
  'KI': 7,
  'KP': 10,
  'KR': 10,
  'KW': 8,
  'KG': 9,
  'LA': 9,
  'LV': 8,
  'LB': 8,
  'LS': 8,
  'LR': 7,
  'LY': 9,
  'LI': 9,
  'LT': 8,
  'LU': 9,
  'MO': 8,
  'MG': 9,
  'MW': 8,
  'MY': 10,
  'MV': 7,
  'ML': 8,
  'MT': 8,
  'MH': 7,
  'MQ': 9,
  'MR': 8,
  'MU': 8,
  'YT': 9,
  'MX': 10,
  'FM': 7,
  'MD': 8,
  'MC': 8,
  'MN': 8,
  'ME': 8,
  'MS': 10,
  'MA': 9,
  'MZ': 9,
  'MM': 9,
  'NA': 9,
  'NR': 7,
  'NP': 10,
  'NL': 9,
  'NC': 6,
  'NZ': 9,
  'NI': 8,
  'NE': 8,
  'NG': 10,
  'NU': 4,
  'NF': 6,
  'MK': 8,
  'MP': 10,
  'NO': 8,
  'OM': 8,
  'PK': 10,
  'PW': 7,
  'PS': 9,
  'PA': 8,
  'PG': 8,
  'PY': 9,
  'PE': 9,
  'PH': 10,
  'PN': 4,
  'PL': 9,
  'PT': 9,
  'PR': 10,
  'QA': 8,
  'RE': 9,
  'RO': 10,
  'RU': 10,
  'RW': 9,
  'BL': 9,
  'SH': 7,
  'KN': 10,
  'LC': 10,
  'MF': 9,
  'PM': 6,
  'VC': 10,
  'WS': 7,
  'SM': 9,
  'ST': 7,
  'SA': 9,
  'SN': 9,
  'RS': 8,
  'SC': 7,
  'SL': 8,
  'SG': 8,
  'SX': 10,
  'SK': 9,
  'SI': 8,
  'SB': 7,
  'SO': 8,
  'ZA': 10,
  'GS': 0,
  'SS': 9,
  'ES': 9,
  'LK': 9,
  'SD': 9,
  'SR': 7,
  'SJ': 0,
  'SE': 9,
  'CH': 9,
  'SY': 9,
  'TW': 9,
  'TJ': 9,
  'TZ': 9,
  'TH': 9,
  'TL': 8,
  'TG': 8,
  'TK': 5,
  'TO': 5,
  'TT': 10,
  'TN': 8,
  'TR': 10,
  'TM': 8,
  'TC': 10,
  'TV': 5,
  'UG': 9,
  'UA': 9,
  'AE': 9,
  'GB': 10,
  'US': 10,
  'UY': 8,
  'UZ': 9,
  'VU': 7,
  'VE': 10,
  'VN': 9,
  'EH': 9,
  'YE': 9,
  'ZM': 9,
  'ZW': 9,
};
